<?php

function drupal_add_js_dependency($stack, $name = false) {
	$config = array(
		'dependencies' => array(
			$stack => array()
		)
	);
	if ($name) {
		$config['dependencies'][$stack][] = $name;
	}
	drupal_add_js($config, 'setting');
}

function jsutils_init() {
	drupal_add_js(drupal_get_path('module', 'jsutils') . '/jsutils.js');
	drupal_add_js(array(
		'absolutePath' => url('/', array('absolute' => TRUE)),
		'basePathResolved' => url('/')
	), 'setting');
}